### ISSUE TITLE
Identifier policy: simplified is not always simple...

### ISSUE THREAD

**Issue by mgilis** [BPC-Exchange-Framework/BPC-Market-Pilot#3]
The identifier rules have been simplified compared to Peppol
Compare BPC
	GLN::5488888002258
With Peppol/EESPA
	0088:5488888002258 (short)
iso6523-actorid-upis::0088:5488888002258: (long)

We had 2 issues: adapting our engine to these simplified identifier definition was the biggest development effort, taking 50% of the total development time. Then we also have to define aliases for current corporates, as the SchemeId’s used are not supported (e.g. VAT registration,…), making bridges between networks more difficult.

**Comment by brittahollandwork** [comment]
Technical Committee Response 5/31: The identifiers included in the limited list were chosen because they have some recognition in the US market. At this point, the committee does not feel the need to review the identifier policy. A temperature check should be conducted again at the end of Wave 2 regarding whether or not the identifier policy should be revised to include other schemeIds.

**Comment by brittahollandwork** [comment]
9/13/22: Two TC temperature checks: 
1.) Majority of participating members agreed that additions to the identifier list are not needed at this time.
2.) Results were even regarding whether or not to apply a global policy the identifiers must be alpha numeric. The group agreed to table this issue until the next week to give committee members time to evaluate further. The committee will determine at that time if this question needs input from the IOC/SC.
