### ISSUE TITLE
Validation rules and validation artefacts

### ISSUE THREAD

**Issue by mgilis** [BPC-Exchange-Framework/BPC-Market-Pilot#5]
To offer comfort to service providers, offering payload agnostic services, we should assume that schematron validation are the  criterium for documents to be injected on the network. As such, these schematrons are mandatary for each document profile exchanged on the network and make these official artefacts for the specification.
Besides that, also attention should be given to the internal integrity of a document. This does not imply the data needs to be presence.  For an invoice we should be confident that amounts when present are consistent, e.g.
•	Total excl + taxes + allowances = totalinclusive
•	Total tax=sum of tax subtotals
•	Total payable = totalinclusive corrected with prepaid amounts
•	Total excl=sum of line items
•	If tax specified on line items, sum should correspond with tax subtotals

**Comment by gkholman** [comment]
While I agree with you regarding the arithmetic calculations you cite, my understanding from an earlier Technical Committee meeting is that the arithmetic is to be excised from the Schematron assertions. This leaves it up to the ERP system to decide if the arithmetic is self-consistent. My view (from the ivory tower) is that the obligation is on Corner 2 to get the arithmetic correct and Corner 3 to reject the document if the arithmetic is incorrect ... and that both should be using the one Schematron set of assertions in order to avoid any ambiguity of interpretation in differing implementations of the arithmetic.

**Comment by brittahollandwork** [comment]
Technical Committee Response 5/31: Arithmetic calculations will not be included in waves 1 or 2. This topic should be discussed again toward the end of Wave 2 and be considered for inclusion in the validation artifacts for Wave 3.

**Comment by brittahollandwork** [comment]
9/20/22: This will be discussed as part of the invoice/credit note profile process.

**Comment by brittahollandwork** [comment]
Closing this issue, as the feasibility of providing ongoing maintenance of validation artifacts beyond the market pilot should be evaluated by the DBNAlliance Board of Directors.
